# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build (Tauri)

on:
  push:
    branches: [ "tauri" ]
  pull_request:
    branches: [ "tauri" ]

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.7'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Linux required packages for Tauri
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install -y libgtksourceview-3.0-dev libappindicator3-dev webkit2gtk-driver xvfb libwebkit2gtk-4.0-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    # - run: npm run build
    # - run: npm run test
    - run: npm run tauri build --release
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.OS }}
        path: src-tauri/target/${{ runner.arch }}/ergo-wallet-*.*
